name: Github action to run tests
on: pull_request
jobs:
  Run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - uses: iterative/setup-dvc@v1
      - name: "Install PyGObject"
        run: |
          sudo apt-get install -y python3-gi python3-gi-cairo gir1.2-secret-1 pkg-config libcairo2-dev gcc python3-dev libgirepository1.0-dev
          pip install pygobject
      - name: "Install GDAL"
        run: |
          sudo apt-get install -y libgdal-dev
      - name: "Install requirements"
        run: pip install -r requirements.txt
      - name: "Pull data"
        run: |
          dvc remote modify efd_data_remote url azure://data/
          dvc remote modify efd_data_remote account_name 'efdml4488431542'
          dvc pull -f
      - name: "Run tests"
        run: |
          export LD_PRELOAD=/lib/x86_64-linux-gnu/libstdc++.so.6:$LD_PRELOAD
          python -m pytest
